"""Shared substrate for the controlled PBC2 simulation (response Section 3.1.2).

The binarised PBC2 cohort provides real predictor sequences; the target column
(ascites) is overwritten with a synthetic binary y_t generated by the same
j1 -> j2 -> j3 rule as the synthetic simulation:

    j1 = bili_high     (real binary column, index 8)
    j2 = albumin_low   (real binary column, index 3)
    j3 = ascites       (the target column we overwrite, index 9)

y_t = 1 with probability P_SUCCESS when (seenfirst AND seensecond) at the start
of step t, else 0. When y_t = 1 the trigger flags reset, matching the synthetic
simulation's reset-on-fire dynamics.

This module holds only the pieces shared across the pbc2-sim driver scripts
(pbc2_controlled_simulation, run_baselines_pbc2_controlled_sim,
architecture_ablations), so they no longer need sibling imports.

Column indices after load_real_data drops id and t. PBC2 binarised order:
hepatomegaly, spiders, edema_present, albumin_low, alkphos_high, ast_high,
platelet_low, protime_high, bili_high, ascites.
"""
import numpy as np

COL_BILI_HIGH = 8        # j1
COL_ALBUMIN_LOW = 3      # j2
COL_ASCITES = 9          # target column we overwrite

# Probability of the synthetic target firing once both triggers are seen.
P_SUCCESS = 0.9


def inject_synthetic_target(sequences, seed):
    """Overwrite COL_ASCITES with a synthetic binary target generated by the
    j1 -> j2 -> j3 rule. Other columns are untouched. Returns the modified
    list plus the z_t (latent flag) and y_t (written target) trajectories
    per patient for diagnostics.
    """
    rng = np.random.default_rng(seed)
    out_seqs = []
    z_per_patient = []
    y_per_patient = []
    for x in sequences:
        T = x.shape[0]
        x_new = x.clone()
        z_t = np.zeros(T, dtype=np.float32)
        y_t = np.zeros(T, dtype=np.float32)

        # Replay the same flag-update logic as SimulatedDataset.generate_data,
        # using REAL binary j1/j2 values and the JUST-WRITTEN target for reset.
        justseenfirst = False
        seenfirst = False
        justseensecond = False
        seensecond = False

        for t in range(T):
            z = 1.0 if (seenfirst and seensecond) else 0.0
            z_t[t] = z
            y_val = 1.0 if (z == 1.0 and rng.random() < P_SUCCESS) else 0.0
            y_t[t] = y_val
            x_new[t, COL_ASCITES] = y_val

            if x[t, COL_BILI_HIGH].item() == 1:
                justseenfirst = True
            if x[t, COL_ALBUMIN_LOW].item() == 1 and seenfirst:
                justseensecond = True
            if y_val == 1.0:
                justseenfirst = False
                justseensecond = False

            seenfirst = justseenfirst
            seensecond = justseensecond

        out_seqs.append(x_new)
        z_per_patient.append(z_t)
        y_per_patient.append(y_t)
    return out_seqs, z_per_patient, y_per_patient
